### PR TITLE
Added Windows content & Data content

### PR DESCRIPTION
**Pull request by ericayhayes**
Hi Briana,

I added the Windows content & Data content Liss requested. Could you review this pull request and merge with yours, so it is published on her site?  Her visualization at NC State is going live this week and we want to make sure users can visit her website and see this content.  

Thanks!
Erica

### CODE REVIEW

**Comment by BrianaCamp** [comment]
Hey @ericayhayes I'm confused about your branch, it's not a branch off this repository?

**Comment by BrianaCamp** [comment]
Ok @ericayhayes this looks good, if you want to go ahead and resolve the conflicts you can merge this, preview it on siteleaf, and if that all looks good, click publish in siteleaf to push it live. Let me know if you  have any questions. Thanks!

**Comment by ericayhayes** [comment]
Hi Bri,

I can't resolve conflicts and accept my own pull request.  Can you accept them?

Thanks,
Erica

**Comment by BrianaCamp** [comment]
ok @ericayhayes, I resolved the conflicts, can you make sure siteleaf preview etc is good? I think it may be better if there are more changes in the future to have your branch from this repo, so you'd need to clone this repo onto your computer so it's much easier to checkout branches, resolve conflicts, etc. Let me know if you have any issues with that approach.

**Pull request merged**
